config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :gyms
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/gym.rb
class Gym < ApplicationRecord
end

app/models/import_csv.rb
class ImportCsv < ApplicationRecord
  def self.import(path)
     CSV.foreach(path, headers: true) do |row|
       Gym.create(
         name: row["name"],
         address: row["address"],
         content: row["content"]
       )
     end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
    def index
        @gyms = Gym.all
    end

    def show
        @gym = Gym.find_by(id: params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gyms/index.html.erb
<div class="container">
    <ul class="gyms-items">
        <% @gyms.each do |gym|%>
            <li class="gyms-item">
                <p><%= link_to gym.name, gym_path(gym) %></p>
                <p><%= gym.content%></p>
            </li>
        <% end %>
    </ul>
</div>

app/views/gyms/show.html.erb
<%= @gym.name%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="sticky-top navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gyms">ジム一覧</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="contents">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="header-img">
    <img class="img-fluid" src="https://picsum.photos/1500/420">

<div class="header-form">
    <%= form_tag('/users/search', method: :get) do %>
    <%= label_tag :名前 %>
    <%= text_field_tag :search_name %>
    <%= label_tag :年齢 %>
    <%= text_field_tag :search_age %>
    <%= submit_tag '検索' %>
    <% end %>
</div>
</div>

<div class="container">
</div>